version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1Project
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/Test1Project
  gitUsername: y509522
  gitBranch: main
